name: Artifacts
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    name: Artifacts
    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
        with:
          config-file: cypress.config.js
      - run: ls -la cypress/videos # Check if videos are created
      - run: ls -la cypress/screenshots # Check if screenshots are created
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
      - uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true
          group: 'CI'
          command: cypress run --browser chrome --record --key ${{ secrets.CYPRESS_RECORD_KEY }} --env video=true
